<?php

namespace NewPlayerMC\RandomHearthAttack;

use pocketmine\entity\Location;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\event\entity\EntityDeathEvent;
use pocketmine\event\player\PlayerDeathEvent;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\NetworkSession;
use pocketmine\player\Player;
use pocketmine\player\PlayerInfo;
use pocketmine\Server;

class CardiacPlayer extends Player
{
    protected int $hearthAttackTick = 0;
    private const NBT_TAG_KEY = "hearthAttackTick";

    public function __construct(Server $server, NetworkSession $session, PlayerInfo $playerInfo, bool $authenticated, Location $spawnLocation, ?CompoundTag $namedtag)
    {
        parent::__construct($server, $session, $playerInfo, $authenticated, $spawnLocation, $namedtag);

        if ($namedtag !== null && $namedtag->getInt(self::NBT_TAG_KEY) !== null) {
            $this->hearthAttackTick = $namedtag->getInt(self::NBT_TAG_KEY);
        } else {
            $this->hearthAttackTick = Main::getInstance()->getRandomTick();
        }
    }

    public function saveNBT(): CompoundTag
    {
        $nbt = parent::saveNBT();
        $nbt->setInt(self::NBT_TAG_KEY, $this->hearthAttackTick);
        $nbt->setInt("ticksLived", $this->ticksLived);

        return $nbt;
    }

    /**
     * Returns the count of ticks the player has to live before having a hearth attack
     * @return void
     */
    public function getTicksToLive(): int {
        return $this->hearthAttackTick;
    }

    public function setTicksToLive(int $ticks): void {
        $this->hearthAttackTick = $ticks;
    }

    public function resetTicksLived(): void {
        $this->ticksLived = 0;
    }

    public function onUpdate(int $currentTick): bool
    {
        var_dump($this->ticksLived . "/" . $this->getTicksToLive());
        if ($this->ticksLived >= $this->getTicksToLive()) {
            $event = new EntityDamageEvent($this, Main::CAUSE_HEARTH_ATTACK, 3.0);
            $event->call();
            $this->attack($event);
        }
        return parent::onUpdate($currentTick); // TODO: Change the autogenerated stub
    }

}