<?php

namespace NewPlayerMC\RandomHeartAttack;

use pocketmine\entity\Location;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\NetworkSession;
use pocketmine\player\GameMode;
use pocketmine\player\Player;
use pocketmine\player\PlayerInfo;
use pocketmine\Server;

class CardiacPlayer extends Player
{
    // Default irrelevant values
    protected int $ticksToLive = 100;
    protected int $maxSprintingTicks = 100;
    
    private const NBT_TAG_TICKSTOL = "ticksToLive";
    private const NBT_TAG_TICKSL = "ticksLived";
    private const NBT_TAG_MAXSPRINTTICKS = "maxSprintTicks";

    public int $sprintingTicks = 0;

    public function __construct(Server $server, NetworkSession $session, PlayerInfo $playerInfo, bool $authenticated, Location $spawnLocation, ?CompoundTag $namedtag)
    {
        parent::__construct($server, $session, $playerInfo, $authenticated, $spawnLocation, $namedtag);

        if ($namedtag !== null &&
            $namedtag->getTag(self::NBT_TAG_TICKSTOL) !== null &&
            $namedtag->getTag(self::NBT_TAG_TICKSL) !== null &&
            $namedtag->getTag(self::NBT_TAG_MAXSPRINTTICKS) !== null
        ) {
            $this->ticksToLive = $namedtag->getInt(self::NBT_TAG_TICKSTOL ,-1);
            $this->ticksLived = $namedtag->getInt(self::NBT_TAG_TICKSL, -1);
            $this->maxSprintingTicks = $namedtag->getInt(self::NBT_TAG_MAXSPRINTTICKS);
        } else {
            $this->setRandomTicksToLive();
            $this->setMaxSprintingTicks();
        }
    }

    public function saveNBT(): CompoundTag
    {
        $nbt = parent::saveNBT();
        $nbt->setInt(self::NBT_TAG_TICKSTOL, $this->ticksToLive);
        $nbt->setInt(self::NBT_TAG_TICKSL, $this->ticksLived);
        $nbt->setInt(self::NBT_TAG_MAXSPRINTTICKS, $this->maxSprintingTicks);

        return $nbt;
    }

    /**
     * Returns the count of ticks the player has to live before having a heart attack
     * @return int
     */
    public function getTicksToLive(): int {
        return $this->ticksToLive;
    }

    public function setRandomTicksToLive(): void {
        // Lets you approximatively between 0 secondes and 300 hours in game before having your heart fail you
        $this->ticksToLive = mt_rand(100, mt_getrandmax()/100);
    }

    public function setMaxSprintingTicks(): void {
        // Lets you sprint between 5 and 180 seconds without dying
        $this->maxSprintingTicks = mt_rand(100, 3600);
    }

    /**
     * Returns the count of ticks you can sprint before having a heart attack
     * @return int
     */
    public function getMaxSprintingTicks(): int
    {
        return $this->maxSprintingTicks;
    }

    public function resetTicksLived(): void {
        $this->ticksLived = 0;
    }

    public function onUpdate(int $currentTick): bool
    {
        if ($this->getGamemode() === GameMode::SURVIVAL()) {
            if ($this->isSprinting()) $this->sprintingTicks++;
            else if ($this->sprintingTicks > 0) $this->sprintingTicks = round($this->sprintingTicks * 0.9);
            if (($this->ticksLived >= $this->ticksToLive) || ($this->sprintingTicks >= $this->maxSprintingTicks)) {
                $this->causeHeartAttack();
            }
        }
        return parent::onUpdate($currentTick); // TODO: Change the autogenerated stub
    }

    public function causeHeartAttack(): void {
        $event = new EntityDamageEvent($this, Main::CAUSE_HEARTH_ATTACK, 3.0);
        $event->call();
        if (!$event->isCancelled()) $this->attack($event);
    }

}