<?php

declare(strict_types=1);

namespace NewPlayerMC\RandomHeartAttack;

use NewPlayerMC\RandomHeartAttack\commands\HeartAttackCommand;
use NewPlayerMC\RandomHeartAttack\libs\CortexPE\Commando\PacketHooker;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\event\Listener;
use pocketmine\event\player\PlayerCreationEvent;
use pocketmine\event\player\PlayerDeathEvent;
use pocketmine\event\player\PlayerMoveEvent;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\SingletonTrait;

class Main extends PluginBase implements Listener {
    use SingletonTrait;

    public const CAUSE_HEARTH_ATTACK = 20;

    protected function onEnable(): void
    {
        parent::onEnable(); // TODO: Change the autogenerated stub

        self::$instance = $this;

        $this->getServer()->getPluginManager()->registerEvents($this, $this);

        if(!PacketHooker::isRegistered()) {
            PacketHooker::register($this);
        }

        $this->getServer()->getCommandMap()->register(
            "heartattack",
            new HeartAttackCommand($this, "heartattack", "Heartattack commands", ['ha'])
        );
    }

    public function onPlayerCreation(PlayerCreationEvent $event) {
        $event->setBaseClass(CardiacPlayer::class);
        $event->setPlayerClass(CardiacPlayer::class);
    }

    public function onDeath(PlayerDeathEvent $event): void {
        $player = $event->getPlayer();
        if ($player instanceof CardiacPlayer) {
            $cause = $player->getLastDamageCause();
            if ($cause instanceof EntityDamageEvent) {
                $c = $cause->getCause();
                if ($c === self::CAUSE_HEARTH_ATTACK) {
                    $event->setDeathMessage($player->getName() . " died of a hearth attack");
                    $player->resetTicksLived();
                    $player->setRandomTicksToLive();
                }
            }
        }
    }

}
